name: testing-builder

on:
  workflow_dispatch:
  push:
    paths:
      - 'testing/**'

jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - name: ROS buildfarm
        uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: humble
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          REPOS_FILE: testing/sources.repos
          PACKAGES_BRANCH: testing
